// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/03/2025, 1:17:23 pm
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Admin/GitHub/name-email-app/frontend-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/composables/**/*.{js,ts,mjs}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/utils/**/*.{js,ts,mjs}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/pages/about.vue","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/pages/index.vue","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/GitHub/name-email-app/frontend-app/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;